/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './breeze-bridge-angular';
import * as import2 from '@angular/http';
class BreezeBridgeAngularModuleInjector extends import0.ɵNgModuleInjector<import1.BreezeBridgeAngularModule> {
  _HttpModule_0:import2.HttpModule;
  _BrowserXhr_1:import2.BrowserXhr;
  _ResponseOptions_2:import2.BaseResponseOptions;
  _XSRFStrategy_3:any;
  _XHRBackend_4:import2.XHRBackend;
  _RequestOptions_5:import2.BaseRequestOptions;
  _Http_6:any;
  _BreezeBridgeAngularModule_7:import1.BreezeBridgeAngularModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.BreezeBridgeAngularModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._BrowserXhr_1 = new import2.BrowserXhr();
    this._ResponseOptions_2 = new import2.BaseResponseOptions();
    this._XSRFStrategy_3 = import2.ɵb();
    this._XHRBackend_4 = new import2.XHRBackend(this._BrowserXhr_1,this._ResponseOptions_2,this._XSRFStrategy_3);
    this._RequestOptions_5 = new import2.BaseRequestOptions();
    this._Http_6 = import2.ɵc(this._XHRBackend_4,this._RequestOptions_5);
    this._BreezeBridgeAngularModule_7 = new import1.BreezeBridgeAngularModule(this._Http_6);
    return this._BreezeBridgeAngularModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_1; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_2; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_3; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_4; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_5; }
    if ((token === import2.Http)) { return this._Http_6; }
    if ((token === import1.BreezeBridgeAngularModule)) { return this._BreezeBridgeAngularModule_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BreezeBridgeAngularModuleNgFactory:import0.NgModuleFactory<import1.BreezeBridgeAngularModule> = new import0.NgModuleFactory<any>(BreezeBridgeAngularModuleInjector,import1.BreezeBridgeAngularModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29ya3NwYWNlL0ZyYW1ld29ya3MvYnJlZXplLmJyaWRnZS5hbmd1bGFyL3NyYy9icmVlemUtYnJpZGdlLWFuZ3VsYXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovV29ya3NwYWNlL0ZyYW1ld29ya3MvYnJlZXplLmJyaWRnZS5hbmd1bGFyL3NyYy9icmVlemUtYnJpZGdlLWFuZ3VsYXIudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
